import Head from 'next/head'
import AppContainer from '@components/AppContainer'
import BookList from "@components/Books/BookList"
import BookListFilters from "@components/Books/BookListFilters"
import { useEffect, useState } from "react"
import toast from "react-hot-toast"
import { useBooks } from "@src/hooks/useBooks"

export default function Home() {
  
  const { getUserBooks, books, loading } = useBooks()
  const [showBooks, setShowBooks] = useState([])

  useEffect(() => {
    getUserBooks()
      .then(data => {
        setShowBooks(data)
      })
      .catch(err => {
        toast.error(err.message)
      })
  }, [])

  useEffect(() => {
    setShowBooks(books)
  }, [books])

  return (
    <>
      <Head>
        <title>Bookshelf - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContainer>
        <header className="pb-10 pt-14">
          <h1 className="text-4xl text-slate-100 font-bold">My Collection</h1>
        </header>
        <BookListFilters />
        <BookList booksInput={showBooks} loading={loading} />
      </AppContainer>
    </>
  )
}

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  }
}
