import Head from 'next/head'
import AppContainer from '@components/AppContainer'
import BookList from "@components/Books/BookList"
import BookListFilters from "@components/Books/BookListFilters"

export default function Home() {
  return (
    <>
      <Head>
        <title>Bookshelf - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContainer>
        <BookListFilters />
        <BookList />
      </AppContainer>
    </>
  )
}
