import Head from 'next/head'
import LoginContainer from '@components/LoginContainer'
import SigninForm from '@src/components/Forms/SigninForm'

export default function Login() {

  return (
    <>
      <Head>
        <title>Bookshelf - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginContainer>
        <div className="bg-gray-800 m-auto max-w-[400px] p-4 rounded-xl">
          <SigninForm />
        </div>
      </LoginContainer>
    </>
  )
}
