import Head from 'next/head'
import LoginContainer from '@components/LoginContainer'
import SignupForm from '@src/components/Forms/SignupForm'

export default function Signup() {

  return (
    <>
      <Head>
        <title>Bookshelf - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginContainer>
        <div className="bg-gray-800 m-auto max-w-[400px] px-6 py-10 rounded-xl">
          <SignupForm />
        </div>
      </LoginContainer>
    </>
  )
}
