name: Virtual-Bookshelf Working Check
run-name: ${{ github.actor }} testing..
on: [push]
jobs:
  check-api-starting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        working-directory: ./api
        run: npm install
      - name: Start Api
        working-directory: ./api
        run: npm run dev
        
  check-client-starting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies and starting
        working-directory: ./client
        run: npm install
      - name: Starting Client
        working-directory: ./client
        run: npm start
